batch_size_train: 25
batch_size_validation: 25
device: cuda:0
diffusion_step: 200
epochs: 125000
final_lr: 1.0e-05
lr: 0.0001
lr_scheduler: step
name: diffusion
num_workers_train: 0
num_workers_validation: 0
optimizer: AdamW
random_seed: 1725349854
record_iteration_loss: false
save_epoch: 5000
save_path: ./training/single_parameter/32/
shuffle_train: true
shuffle_validation: true
validation_epoch_frequency: 0
warmup_epoch: 0
